services:
    cassandra:
        image: docker.io/library/cassandra:5.0.5
        container_name: cassandra
        volumes:
            - cassandra-data:/var/lib/cassandra
        ports:
            - 9042:9042
volumes:
    cassandra-data: