services:
    mongodb:
        image: docker.io/library/mongo:8.0.12
        container_name: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: "root"
            MONGO_INITDB_ROOT_PASSWORD: "admin"
        volumes:
            - mongodb-data:/data/db
            - mongodb-config:/data/configdb
        ports:
            - 27017:27017
        healthcheck:
            test: [
                "CMD",
                "mongosh",
                "mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@localhost:27017/admin",
                "--eval",
                "\"db.runCommand('ping')\"",
                "--quiet"
            ]
            interval: 5s
            timeout: 5s
            retries: 5
            start_period: 10s
    mongo-express:
        image: docker.io/library/mongo-express:1.0.2-20-alpine3.19
        container_name: mongo-express
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: "root"
            ME_CONFIG_MONGODB_ADMINPASSWORD: "admin"
            ME_CONFIG_MONGODB_SERVER: "mongo"
        ports:
            - 8888:8081
        depends_on:
            mongodb:
                condition: service_healthy
volumes:
    mongodb-data:
    mongodb-config: