services:
    postgresql:
        image: docker.io/library/postgres:17.5
        container_name: postgres
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "admin"
            POSTGRES_DB: "postgres"
        volumes:
            - postgresql-data:/var/lib/postgresql/data #18+ >>> /var/lib/postgresql
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
            interval: 3s
            timeout: 5s
            retries: 5
            start_period: 10s
volumes:
    postgresql-data:
