services:
    mailpit:
        image: docker.io/hashicorp/vault:1.21
        container_name: vault
        environment:
            VAULT_DEV_ROOT_TOKEN_ID: "root"
            VAULT_ADDR: "http://0.0.0.0:8200"
        ports:
            - 8200:8200
        cap_add:
            - IPC_LOCK
